### ISSUE TITLE
Is it a wrong google drive link?

### ISSUE THREAD

**Issue by baoyouren** [cwfparsonson/retro_branching#1]
Hi, I couldn't find retro_branching_paper_validation_instances in google drive. Is the google drive link wrong?

**Comment by cwfparsonson** [comment]
Hi,

Apologies, the Google drive link was broken. I've updated the README - please try the following and let me know if there are any issues:

```
gdown --folder https://drive.google.com/drive/u/0/folders/1nZDsofdfmXvD6Y9sYAOse0eK90NLQOOK
```
