### ISSUE TITLE
how long does the training take?

### ISSUE THREAD

**Issue by alexayue** [cwfparsonson/retro_branching#2]
Does the training run all 500 0000 epochs?  how long does the training take?

**Comment by cwfparsonson** [comment]
Training times depend on what kind of device(s) you use to train the model on. We trained on one A100 GPU which took up to 6 days to get the results shown in the paper for the largest instances (refer to the [retro branching paper](https://arxiv.org/pdf/2205.14345.pdf), specifically Appendix A.2 'Training Time and Convergence', for further details). You could speed up these training times if you distribute the training across multiple GPUs.
