### ISSUE TITLE
Ran out of iterations issue

### ISSUE THREAD

**Issue by jonaaf** [cwfparsonson/retro_branching#3]
Hi Christopher,

first of all congrats for the great work and thank you for making it available.  I have been exploring it for the past couple of weeks and I have downloaded the trained weights and validation instances. Everything works swiftly for the set covering problems (both the 165x260 and 500x1000 instances), however as soon as I change to other problem, say combinatorial auction, the output is only "ran out of iterations". I have performed already some debugging however I cannot understand why this is happening, neither have I found a solution to it.

Below you find the code I executed from the console (the co_class and co_class_kwargs parameters have been adjusted accordingly on the validator.yaml file) :
 python experiments/validator.py --config-path=configs --config-name=validator.yaml environment.scip_params=gasse_2019 instances.co_class=combinatorial_auction instances.co_class_kwargs.n_items=10 instances.co_class_kwargs.n_bids=50 experiment.agent_name=retro experiment.device=cpu 

Thanks a lot in advance for your attention.
Best regards,
Jonathan

**Comment by cwfparsonson** [comment]
Hi @jonaaf 

Thank you for your interest in our work!

Do any instances get solved and saved to the validation data file? Some of the smaller instances might be being pre solved by SCIP, which means that of the 100 validation instances, the branching agent being tested would only have been applied to a sub-set of the instances (e.g. if 5 instances are pre-solved, the validation data file should contain the info for the 95 remaining instances the branching agent was used for). This would result in a 'Ran out of iterations' warning being printed to the terminal, but I do not think it should result in the script crashing. If it does, could you please copy-paste the full error message from your terminal?

Thanks 
Chris

**Comment by jonaaf** [comment]
Hi Christopher,

thanks a lot for the short reply. Yes as you pointed out the script does not crash, instances are loaded, paths are set etc.. but instead of obtaining the normal output (namely: Run Time | Nodes |  LP iters | Solve time) only "Ran out of iterations" is displayed for each instance.
What I just did is shortly train the retro agent for the Combinatorial Auction Problem with 30 items and 150 bids, and when running on 300 validation instances only around 140 are solved by the agent, the rest ran out of iterations. Is it possible to deactivate this "pre solve" on SCIP in order to get the agent to solve this instances as well or maybe something similar? I have briefly looked at the different SCIP parameters (https://www.scipopt.org/doc/html/PARAMETERS.php) in order to enable/disable presolving on the scip_params files (e.g. gasse_2019_scip_params.py) but there are just too many different parameters. Any comments on this would be very much appreciated.

Thanks once again for taking the time to reply!
Best regards,
Jonathan

**Comment by cwfparsonson** [comment]
Hi @jonaaf 

I've looked into this and you are indeed correct, with the `scip` settings given the small instances get pre-solved. As you have also figured out, this is because we are not disabling enough of the pre-solving functionality of `scip`. 

To prevent the majority of instances being pre-solved and to repeat the results as they stand in the paper for the small instances, you should set `environment.scip_params=default` when you call the validator script.

I.e. the command you used before should be adjusted to:

```
python experiments/validator.py --config-path=configs --config-name=validator.yaml environment.scip_params=default instances.co_class=combinatorial_auction instances.co_class_kwargs.n_items=10 instances.co_class_kwargs.n_bids=50 experiment.agent_name=retro experiment.device=cpu
```

This will call the parameters in `retro_branching/src/scip_params/default_scip_params.py` to disable some of the `scip` pre-solving functionality. 

We will update the instructions for repeating the paper's results accordingly - many thanks for spotting this! Please let me know if you have any further issues.

Best wishes,
Chris

**Comment by jonaaf** [comment]
Hi Chris,

Indeed when changing the scip_parameters to default a much larger number of instances is solved via the agent. Thank you once again for your attention and in case something else shows up i´ll come back to you.

Best regards,
Jonathan
